add files for build and start with docker
kevinkk525/SmartServer pull request #1
Opened 2020-02-14 21:44 UTC by dasTholo

new file:   Dockerfile to build a docker image
new file:   requirements.txt for pip install
modified:   README.md at #4. Install and run with docker

2020-02-15 14:00 UTC, kevinkk525 requested changes
Thank you for this PR! It is an interesting idea to put this into a docker container. I tried it and it works fine. Thanks.

There are just a few things that you could change:

2020-02-15 14:00 UTC, kevinkk525 commented on README.md
> +Clone this Repo and create your personally _config.py_ file.
*repo
*personal

2020-02-15 14:00 UTC, kevinkk525 commented on README.md
> +Build an docker Image with
Build *a docker *image

2020-02-15 14:00 UTC, kevinkk525 commented on README.md
> +You can find the SmartServer Logs with ```docker logs smartserver -f```
This is only a very detailed log with debug output.
The log file written by the application is in the "Logs" directory as configured in config.py.

2020-02-15 14:00 UTC, kevinkk525 commented on README.md
> +docker run -d -v "$PWD":/usr/src/myapp --name smartserver smartserver:latest
maybe add an explanation to $PWD and how to change having Logs in a different location?

Also /usr/src/myapp seems to be wrong. The correct path in my case is:
/usr/src/app
This is the work directory of the image: https://github.com/kevinkk525/SmartServer/pull/1/files#diff-3254677a7917c6c01f55212f86c57fbfR3
Otherwise the "Logs" directory will be created inside the container.

Also there are log files for each device in the directory "Clients" which gets created in $PWD

2020-02-15 14:00 UTC, kevinkk525 commented on README.md
> +docker build -t smartserver .
Isn't there a "cd SmartServer" missing first?

2020-02-16 07:21 UTC, dasTholo commented
You're right! My English is rather poor and it was probably too late. Thank you for your review! And bit thanks for this Project!

2020-02-16 07:30 UTC, merged

2020-02-16 07:30 UTC, kevinkk525 commented
No problem. Thank you for the Pull Request!